### PR TITLE
Made the build publishable

### LINKED ISSUE #11: Publish to Maven Central
Please publish this library to Maven Central. See http://central.sonatype.org/pages/ossrh-guide.html if you've never done this before.

### PR DESCRIPTION
**Pull request by knshiro**
Hi,

This should fix #11.

I switched your build tool to gradle (http://gradle.org/) and made your library publishable on bintray (https://bintray.com/) thanks to gradle-bintray-plugin (https://github.com/bintray/gradle-bintray-plugin).

You just need to add in `~/.gradle/gradle.properties`
```
bintrayUser = user
bintrayApiKey = your-bintray-api-key   // Not password!!
```
Or use environment varialbles (for example if you want to deploy from travis)
```
export BINTRAY_USER=user
export BINTRAY_API_KEY=your-bintray-api-key
```
Then use:
```
./gradlew bintrayUpload
```
The build launches your tests without the "test_with_php" system properties but you can also activate it by using the environment variable:
```
export TEST_WITH_PHP=yes
```

### CODE REVIEW

**Comment by knshiro** [comment]
@mariten Making a new PR doesn't make new commits so the build on travis is not re-triggered.
You can retrigger it manually though there should be a button on the top right, on the build page:
https://travis-ci.org/mariten/kanatools-java/builds/107165432

**Comment by mariten** [comment]
Hi @knshiro ,
Thanks again for adding this publishable capability to this repository.  This looks good so I'm going to merge it.

I've been playing around with Gradle a lot this past week and learned a lot.  I can't seem to get Travis CI working though -- I'm in contact with them over why the same Git branch works on one namespace (yours) and not another (mine).

For the time being, I'm going to restore the Ant `build.xml` and its associated functionality as I've been testing it locally and its existance doesn't conflict with the way Gradle builds.

Thanks again!

**Comment by knshiro** [comment]
Awesome thanks! 
I removed the ant build because I was afraid it would take precedence over gradle in Travis.

**Comment by mariten** [comment]
I think I'll leave both in there for now to leave backwards compatibility for now, and have Travis test both since they apparently don't conflict with each other...at least once I figure out why there's a memory issue on mine.

I'll add some change notes, make a new version, and push your change to `master` soon.  Then I'll make it available via BinTray as you advised above, and then hopefully it will reach a wider audience!

Thanks again!

**Comment by knshiro** [comment]
I'm glad I could help :)
If you need anything else during your publishing phase don't hesitate to
ping me.
FYI: since I needed it for one of my project, here is the published
artifact on our own repository:
https://bintray.com/en-japan/maven-oss/kanatools-java/view

**Comment by mariten** [comment]
Hi @knshiro 

Thanks again for the pull request and including the Bintray plugin!  Publishing to Bintray and JCenter proved quite easy.  Syncing that artifact on JCenter to Maven Central on the other hand was quite convoluted and required many additional steps, but it is finally done and available on there as well.

You'd set my group as `com.github.mariten`, but before publishing I've registered it as `com.mariten`. I'm very thrilled to see you're using it in your japanese-tokenizer!  If you want to use the "official" version, feel free to call it in your dependency like this:

```
"com.mariten" % "kanatools" % "1.3.0"
```

I lived in Japan for 9 years, until recently actually, when I moved to my company's US office in San Francisco.  I never used en-japan while there but I have two friends who work there and they said good things about the developers there.  Best of luck with your tokenizer!

**Pull request merged**
