### PR TITLE
made the build publishable

### LINKED ISSUE #11: Publish to Maven Central
Please publish this library to Maven Central. See http://central.sonatype.org/pages/ossrh-guide.html if you've never done this before.

### PR DESCRIPTION
**Pull request by knshiro**
Hi,

This should fix #11.

I switched your build tool to gradle (http://gradle.org/) and made your library publishable on bintray (https://bintray.com/) thanks to gradle-bintray-plugin (https://github.com/bintray/gradle-bintray-plugin).

You just need to add in `~/.gradle/gradle.properties`
```
bintrayUser = user
bintrayApiKey = your-bintray-api-key   // Not password!!
```
Or use environment varialbles (for example if you want to deploy from travis)
```
export BINTRAY_USER=user
export BINTRAY_API_KEY=your-bintray-api-key
```
Then use:
```
./gradlew bintrayUpload
```

The build launches your tests without the "test_with_php" system properties but you can also activate it by using the environment variable:
```
export TEST_WITH_PHP=yes
```

### CODE REVIEW

**Comment by knshiro** [comment]
About the failed build, I checked it's only a memory error. It should pass if you rerun it.
It just worked on our travis: https://travis-ci.org/en-japan/kanatools-java/builds/107164321

**Comment by mariten** [comment]
Hi @knshiro 
Thanks for the first pull request!  Let me look this over and play around locally with gradle (I haven't used it personally but have heard good things about it) so I get a good grasp on what has changed.

The failing on Travis CI is a problem though.  I saw it works on your en-japan one, but it has to work on the normal one as well -- I'll experiment with this.

**Comment by mariten** [comment]
@knshiro Actually would you mind remaking this pull request and directing it to `staging`, not `master`?
That way:

1. Can see if it succeeds on Travis CI again before putting in `master` (aka, releasing it)
2. If merged, I will need to update the documentation prior to release.

Thanks again for fixing this up, and really appreciate you kept in the JUnit test running and Jacoco coverage process

**Comment by knshiro** [comment]
@mariten Ok sure I'm closing this PR and reopening another on staging

**Pull request closed without merging**
